<div class="container clear-bottommargin clearfix">
      <div class="heading-block center">
           <div class="fancy-title title-center title-dotted-border topmargin-sm">
               <h2><span>Our products and services</span></h2></div>
<span>With the following services we are able to offer you a broad spectrum of products, find innovative solutions which are appropriate for your wealth management needs.</span>
</div>
<div class="row">
  
<div class="col-lg-4 bottommargin">
<img data-animate="fadeInLeftBig" src="images/services2.png" alt="ccc plc services" class="center-block">
</div>
<div class="col-lg-4 col-md-6 topmargin bottommargin">
<div class="col_full">
<div class="feature-box fbox-rounded fbox-effect">
<div class="fbox-icon">
<a href="#"><i class="icon-credit-card i-alt"></i></a>
</div>
<h3>ATM Services</h3>
<p> CCC Plc places ATMs are open 24/7 in its branches for clients....</p>
</div>
</div>
<div class="col_full">
<div class="feature-box fbox-rounded fbox-effect">
<div class="fbox-icon">
<a href="#"><i class="icon-hand-holding-usd i-alt"></i></a>
</div>
<h3>Credit Facilities</h3>
<p> Utility loans, Line of credit, Business loans, ...</p>
</div>
</div>
<div class="col_full ">
<div class="feature-box fbox-rounded fbox-effect">
<div class="fbox-icon">
<a href="#"><i class="icon-et-refresh i-alt"></i></a>
</div>
<h3>Transfer Rates</h3>
<p>Transfer your money at cheap and affordable rates..</p>
</div>
</div>
<div class="col_full nobottommargin">
<div class="feature-box fbox-rounded  fbox-dark fbox-effect">
<div class="fbox-icon">
<a href="#"><i class="icon-globe-americas i-alt"></i></a>
</div>
<h3>Others</h3>
<p> International Transfers via Western Union, Orange Money, MTN Mobile Money... .</p>
</div>
</div>
</div>
<div class="col-lg-4 col-md-6 topmargin bottommargin">
<div class="col_full">
<div class="feature-box fbox-rounded fbox-dark fbox-effect">
<div class="fbox-icon">
<a href="#"><i class="icon-et-wallet i-alt"></i></a>
</div>
<h3>Current Accounts</h3>
<p>Enables account holders to benefit from credit facilities....</p>
</div>
</div>
<div class="col_full">
<div class="feature-box fbox-rounded  fbox-dark fbox-effect">
<div class="fbox-icon">
<a href="#"><i class="icon-realestate-moneybox i-alt"></i></a>
</div>
<h3>Savings Accounts</h3>
<p>Your finances are secured and guaranteed..</p>
</div>
</div>

<div class="col_full ">
<div class="feature-box fbox-rounded  fbox-dark fbox-effect">
<div class="fbox-icon">
<a href="#"><i class="icon-medical-i-billing  i-alt"></i></a>
</div>
<h3> Term/time deposit </h3>
<p> Interest is calculated and paid based on amount deposited..</p>
</div>
</div>
<div class="col_full nobottommargin">
<div class="feature-box fbox-rounded  fbox-dark fbox-effect">
<div class="fbox-icon">
<a href="#"><i class="icon-credit-card1 i-alt"></i></a>
</div>
<h3>GIMAC</h3>
<p>We offer GIMAC ATM cards. Withdraw from any ATM at anytime</p>
</div>
</div>
</div>
</div>
</div>